# Generated by Django 4.0.2 on 2022-02-20 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_picker', '0002_excludedrestaurants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excludedrestaurants',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restaurant_picker.restaurant'),
        ),
    ]
