# Generated by Django 4.0.2 on 2022-02-20 18:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_picker', '0003_alter_excludedrestaurants_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='excludedrestaurants',
            name='date',
            field=models.DateField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='excludedrestaurants',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='excluded', to='restaurant_picker.restaurant'),
        ),
    ]
