# Generated by Django 4.0.2 on 2022-02-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_picker', '0004_excludedrestaurants_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excludedrestaurants',
            name='date',
            field=models.DateField(),
        ),
    ]
