# Generated by Django 4.0.2 on 2022-02-20 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_picker', '0005_alter_excludedrestaurants_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excludedrestaurants',
            name='restaurant',
        ),
    ]
