# Generated by Django 4.0.2 on 2022-02-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_picker', '0007_excludedrestaurants_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excludedrestaurants',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
