# Generated by Django 4.0.2 on 2022-02-20 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_restaurants_to_exclude'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
